blog/api/urls.py
from django.urls import path

from blog.api.views import (
    api_detail_blog_view,
    api_update_blog_view,
    api_delete_blog_view,
    api_create_blog_view,
    ApiBlogListView,
    )

app_name = 'blog'

urlpatterns = [
    path('<slug>/', api_detail_blog_view, name='detail'),
    path('<slug>/update', api_update_blog_view, name='update'),
    path('<slug>/delete', api_delete_blog_view, name='delete'),
    path('create', api_create_blog_view, name='create'),
    path('list', ApiBlogListView.as_view(), name='list'),
]

blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name='create'),
    path('<slug>/', detail_blog_view, name='detail'),
    path('<slug>/edit', edit_blog_view, name='edit'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from personal.views import(    
    home_screen_view,
) 
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view
)
from blog.api.views import api_detail_blog_view


urlpatterns = [
    path('', home_screen_view, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')), #Means any urls written in blogs.urls will go like this - blog/create or blog/update.
    path('register/', registration_view, name='register'),
    path('account/', account_view, name='account'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),

    #REST API Urls
    path('api/blog/', include('blog.api.urls', 'blog_api')),
    path('api/account/', include('account.api.urls', 'account_api')),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)

    #We are using built-in views for all the password related views, also created custom urls to path the views because we already made
    # a path using 'account' url, also made a custom templates to display.
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models

# Create your models here.
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

# A location to save the blog imgs
def upload_location(instance, filename):
    #A defined format to save the blog images
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
        author_id = str(instance.author.id),
        title = str(instance.title),
        filename = filename,
    )
    return file_path

class BlogPost(models.Model):
    title                   = models.CharField(max_length=50, null=False, blank=False)
    body                    = models.TextField(max_length=5000, null=False, blank=False)
    image                   = models.ImageField(upload_to=upload_location, null=False, blank=False)
    date_published          = models.DateTimeField(auto_now_add=True, verbose_name="date_published")
    date_updated            = models.DateField(auto_now=True, verbose_name="date_updated")
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) #It looks for an authenticated account and maps a foreign key relationship with the account table to the author.
    #CASCADE - Deletes everything that is related to the author like images, title, body, but not the actual account that it is assciated with it.
    slug                    = models.SlugField(blank=True, unique=True) #Just an URL, that is unique for the every blog post.

    def __str__(self):
        return self.title

#When the Blog Post of a user gets deleted, then also deletes the image from the DB, not just the ref link, but the whole img of the blog post.
@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

# Brfore saving the blog post, run this function. It basically, sets a unique url for every blog post by considering the username & the title of the blog.
def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

blog/forms.py
from django import forms
from blog.models import BlogPost

class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image'] #Fields that I'm intreseted in, and to play with in this form, from BlogPost model.


class UpdateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ('title', 'body', 'image')
    
    #A custom save method for the blog update form. This function only called if the commit is true.
    def save(self, commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']

        #If the form has a new image
        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data['image']
        
        if commit:
            blog_post.save()

        return blog_post

blog/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.authentication import TokenAuthentication
from rest_framework.filters import SearchFilter, OrderingFilter

from account.models import Account
from blog.models import BlogPost
from blog.api.serializers import BlogPostSerializer
from django.http import JsonResponse


@api_view(['GET']) #Because we only want to display/view the data.
@permission_classes((IsAuthenticated, )) #No one without the Authentication Token is able to get the view.
def api_detail_blog_view(request, slug):

    #If the blog exist 
    try:
        blog_post = BlogPost.objects.get(slug=slug) #Get all the blog post model objects
    except BlogPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND) #Return the RESTAPI Response with the status & message of 404 not found.
    
    if request.method == 'GET':
        serializer = BlogPostSerializer(blog_post)
        return Response(serializer.data) #Return the serialized data


@api_view(['PUT', ]) #Because we want to update the blog.
@permission_classes((IsAuthenticated, )) 
def api_update_blog_view(request, slug):

    #If the blog exist
    try:
        blog_post = BlogPost.objects.get(slug=slug) #Get all the blog post model objects
    except BlogPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND) #Return the RESTAPI Response with the status & message of 404 not found.
    
    user = request.user
    if blog_post.author != user:
        return Response({'response': "You are not authorize to edit this blog."})
    
    if request.method == 'PUT':
        serializer = BlogPostSerializer(blog_post, data = request.data)
        data = {} #Just like the context

        #Just like we used to do with the django forms
        if serializer.is_valid():
           serializer.save() 
           data['success'] = "updated successfully"
           return Response(data=data) #Return the updated data
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST) #Return the error that why serializer is not valid.
    

@api_view(['DELETE', ]) #Because we want to delete the blog.
@permission_classes((IsAuthenticated, )) 
def api_delete_blog_view(request, slug):
    #If the blog exist
    try:
        blog_post = BlogPost.objects.get(slug=slug) #Get all the blog post model objects
    except BlogPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND) #Return the RESTAPI Response with the status & message of 404 not found.
    
    user = request.user
    if blog_post.author != user:
        return Response({'response': "You are not authorize to delete this blog."})
    
    if request.method == 'DELETE':
        operation = blog_post.delete() #Delete that blog
        data = {}
        if operation: #if operation was successful
            data['success'] = "Deleted successfully"
        else:
            data["failure"] = "Delete failed"
        return Response(data=data) #Return the respective data
    

@api_view(['POST', ]) #Because we only want to display/view the data.
@permission_classes((IsAuthenticated, ))
def api_create_blog_view(request):
    account = request.user

    #Bcz the model has author field, and we are getting the account above here. Also, BlogPostSerializer doesnt have any account/author field.
    blog_post = BlogPost(author=account)

    if request.method == 'POST':
        serializer = BlogPostSerializer(blog_post, data=request.data) #Passing the blog post that has already an author attached to it.
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


#Pagination. (You can define number of posts per page from the settings)
class ApiBlogListView(ListAPIView):
    queryset = BlogPost.objects.all()
    serializer_class = BlogPostSerializer
    authentication_classes = (TokenAuthentication, )
    permission_classes = (IsAuthenticated, )
    pagination_class = PageNumberPagination
    filter_backends = (SearchFilter, OrderingFilter)
    search_fields = ('title', 'body', 'author__username') #Since the author is the Foreign Key of the username, so we have to wrrite like this 'author__username' for the search fields.

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import BlogPost
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
from account.models import Account
from django.db.models import Q
from django.http import HttpResponse


# Create your views here.
def create_blog_view(request):

    context = {}
    user = request.user

    if not user.is_authenticated:
        return redirect('login')
    
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False) 
        #why not only form.save(), because before saving this form, we also have to consider the author name of the blogpost, that is not coming automatically.
        author = Account.objects.filter(email=user.email).first() #Select the first item from the query set.
        obj.author = author #Get the account object for the author
        obj.save() #And, set the account object. Now the form has been save completely.
        form = CreateBlogPostForm() #Now that we have created our blog using the form, now reset the form as it was initially.
    
    context['form'] = form

    return render(request, 'blog/create_blog.html', context)


def detail_blog_view(request, slug):
    context = {}

    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post

    return render(request, 'blog/detail_blog.html', context)


def edit_blog_view(request, slug):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return render('login')
    
    blog_post = get_object_or_404(BlogPost, slug= slug)

    if blog_post.author != user:
        return HttpResponse('You are not the author of that post.')
    
    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Blog has been updated successfully"
            blog_post = obj
    else:
        form = UpdateBlogPostForm(
            initial={
                'title': blog_post.title,
                'body': blog_post.body,
                'image': blog_post.image
            }
        )
    context['form'] = form
    return render(request, 'blog/edit_blog.html', context)

def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ") #Split the query into words. python install 24 => [python, install, 24]
    for q in queries:
        posts = BlogPost.objects.filter(
            # Q lookups, are used to make the query.
            # icontaines removes the case sensitivity of the query.
            Q(title__icontains=q) |
            Q(body__icontains=q)
        ).distinct() #distinct() removes the duplicate entries from the query set. All of the posts that comes will be unique.

        for post in posts:
            queryset.append(post)

    return list(set(queryset)) #Return the unique posts that are found by the query.

blog/templates/blog/snippets/blog_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center">
        <!-- Previous Page Link -->
        <!-- Only shows if there are previous pages available -->
        {% if blog_posts.has_previous %}
            <li class="page-item">
                <!-- 
                    Creates link to previous page
                    Maintains search query if it exists (q parameter)
                    blog_posts.previous_page_number gets the previous page number
                -->
              <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
            </li>
        {% endif %}

        <!-- Page Numbers -->
        <!-- Loops through all available pages -->
        {% for i in blog_posts.paginator.page_range %}
            {% if blog_posts.number == i %}
             <!-- Highlights current page with active class -->
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
            {% else %}
             <!-- Regular page number links -->
             <!-- Maintains search query if it exists -->
                <li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        <!-- Next Page and Last Page Links -->
        <!-- Only shows if there are more pages ahead -->
        {% if blog_posts.has_next %}
        <!-- Next page link -->
            <li class="page-item">
                 <!-- 
                    Creates link to next page
                    Maintains search query if it exists
                    blog_posts.next_page_number gets the next page number
                -->
              <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
            </li>
            <!-- Last page link -->
            <li class="page-item">
                <!-- 
                    Creates link to last page
                    blog_posts.paginator.num_pages gets total number of pages
                -->
              <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
    </nav>
    </div>
    <!-- end pagination-->

blog/templates/blog/snippets/blog_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width:100%;
	}
	.card-body{
		padding: 20px;
	}
</style>

{% if blog_post %}
<div class="container">
	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto">
			<a href="{% url 'blog:detail' post.slug %}">
				<img class="card-img-top" src="{{blog_post.image.url}}">
			</a>
			
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'blog:detail' post.slug %}">
					<h2 class="card-title">{{blog_post.title}}</h2>
				</a>
				<p class="card-text">{{blog_post.body|safe|truncatechars:180}}</p>
				{% if blog_post.author == request.user %}
					<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Edit</a>
				{% endif %}
			</div>
			<div class="card-footer text-muted">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author}}
			</div>
		</div>
	</div>
</div>

{% else %}
	<div class="container">
		<div class="row">
			<div class="card m-auto">
				<div class="card-body mt-2 mb-2">
					<h2 class="card-title">
						No Blog Post Found
					</h2>
					<p class="card-text">There were no results matching your search: {{query}}</p>
				</div>
			</div>
		</div>
	</div>
{% endif %}